name: ðŸ› Bug Report
description: Report a bug or unexpected behavior in ControlFlow
labels: [bug, pending]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to ControlFlow! ðŸ™

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're experiencing and what you would expect to happen instead.

        Provide as much detail as possible to help us understand and solve your problem quickly.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please provide a self-contained,
        [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        import controlflow as cf

        ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Version Information
      description: |
        Please provide information about your ControlFlow version, Prefect version, Python version, and OS.

        To get this information, run the following command in your terminal and paste the output below:

        ```bash
        controlflow version
        ```

        If there is other information that would be helpful, such as LLM provider, model, or package version, please include it as well.
      render: Text
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. This could include:
        - The full error message and traceback (if applicable)
        - Information about your environment (e.g., virtual environment, installed packages)
        - Steps to reproduce the issue
        - Any recent changes in your code or setup that might be relevant
